Credissimo\User\Domain\Model\User:
    repositoryClass: Credissimo\User\Infrastructure\Repository\Doctrine\ORM\DoctrineUserRepository
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        name:
            type: string
            length: 255

    OneToMany:
        products:
            targetEntity: Product
            mappedBy: product
