security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: login
                check_path: login
                default_target_path: homepage
#                csrf_provider: form.csrf_provider # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true
            logout:
                 path:   fos_user_security_logout
                 default_target_path: login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_FULLY_AUTHENTICATED }
        - { path: ^/admin$, role: ROLE_ADMIN }
        - { path: ^/product, role: ROLE_ADMIN }
