Credissimo\Shop\Domain\Model\Attribute:
    repositoryClass: Credissimo\Shop\Infrastructure\Repository\Doctrine\ORM\DoctrineAttributeRepository
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 32
            unique: true
            nullable: false
        label:
            type: string
            length: 255
        type:
            type: smallint
            nullable: false

    manyToOne:
        category:
            targetEntity: Credissimo\Shop\Domain\Model\Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
