Credissimo\Shop\Domain\Model\Attribute:
    repositoryClass: Credissimo\Shop\Infrastructure\Repository\Doctrine\ORM\DoctrineAttributeRepository
    type: entity
    table: attribute
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 32
            unique: true
            nullable: false
        label:
            type: string
            length: 255
        type:
            type: smallint
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true

    ManyToOne:
        category:
            targetEntity: Category
            inversedBy: attributes
            joinColumn:
                name: category_id
                referencedColumnName: id
