Credissimo\Shop\Domain\Model\Category:
    repositoryClass: Credissimo\Shop\Infrastructure\Repository\Doctrine\ORM\DoctrineCategoryRepository
    type: entity
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 32
            unique: true
            nullable: false
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    OneToMany:
        products:
            targetEntity: Product
            mappedBy: category
        attributes:
            targetEntity: Attribute
            mappedBy: category
