Credissimo\Shop\Domain\Model\Manufacture:
    repositoryClass: Credissimo\Shop\Infrastructure\Repository\Doctrine\ORM\DoctrineManufactureRepository
    type: entity
    table: manufacture
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 32
            unique: true
            nullable: false
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    OneToMany:
        products:
            targetEntity: Product
            mappedBy: manufacture
    ManyToOne:
        category:
            targetEntity: Category
            inversedBy: manufactures
            joinColumn:
                name: category_id
                referencedColumnName: id
