Credissimo\Shop\Domain\Model\Product:
    repositoryClass: Credissimo\Shop\Infrastructure\Repository\Doctrine\ORM\DoctrineProductRepository
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        description:
            type: string
        model:
            type: string
            length: 32
        yearOfManufacture:
            type: datetime
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        status:
            type: smallint
            nullable: true
            length: 1
    manyToOne:
        category:
            targetEntity: Credissimo\Shop\Domain\Model\Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        manufacture:
            targetEntity: Credissimo\Shop\Domain\Model\Manufacture
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                manufacture_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Credissimo\User\Domain\Model\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
