Credissimo\Shop\Domain\Model\ProductImage:
    repositoryClass: Credissimo\Shop\Infrastructure\Repository\Doctrine\ORM\DoctrineProductImageRepository
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        src:
            type: string
            length: 255
        title:
            type: string
            length: 255
            options:
                fixed: false
    manyToOne:
        product:
            targetEntity: Credissimo\Shop\Domain\Model\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
